version: "3.8"
services:
  node-api:
    image: node:14
    container_name: node-api
    command: bash -c "npm install && npm run start"
    user: "node"
    working_dir: /home/node/app
    restart: on-failure
    volumes:
      - ./:/home/node/app
    ports:
      - 3001:3001
